#!/usr/bin/env ruby
# frozen_string_literal: true

require 'csv'
require 'json'
require 'net/http'
require 'optparse'
require 'uri'
require 'fileutils'
require 'time'

OPTIONS = {
  store_domain: 'theforestrystudio.com',
  products_json: nil,
  issues_csv: nil,
  missing_shipping_csv: nil,
  output_dir: 'reports',
  settings_data: 'config/settings_data.json',
  max_pages: 50
}.freeze

VALID_GTIN_LENGTHS = [8, 12, 13, 14].freeze

def strip_html(text)
  text.to_s.gsub(/<[^>]*>/, ' ').gsub(/\s+/, ' ').strip
end

def parse_options
  options = OPTIONS.dup

  parser = OptionParser.new do |opts|
    opts.banner = "Usage: ruby scripts/google-merchant-audit.rb [options]"

    opts.on('--store-domain DOMAIN', 'Store domain to audit (default: theforestrystudio.com)') do |value|
      options[:store_domain] = value
    end

    opts.on('--products-json PATH', 'Use local Shopify products JSON file instead of fetching /products.json') do |value|
      options[:products_json] = value
    end

    opts.on('--issues-csv PATH', 'Merchant Center product issues CSV export (product_issues_*.csv)') do |value|
      options[:issues_csv] = value
    end

    opts.on('--missing-shipping-csv PATH', 'Missing shipping report CSV export (issue_report_*_Missing_shipping_information*.csv)') do |value|
      options[:missing_shipping_csv] = value
    end

    opts.on('--output-dir PATH', 'Directory for generated reports (default: reports/)') do |value|
      options[:output_dir] = value
    end

    opts.on('--settings-data PATH', 'Theme settings_data.json path (default: config/settings_data.json)') do |value|
      options[:settings_data] = value
    end

    opts.on('--max-pages N', Integer, 'Safety cap for products.json page fetches (default: 50)') do |value|
      options[:max_pages] = value
    end
  end

  parser.parse!
  options
end

def http_get_json(url)
  uri = URI(url)
  request = Net::HTTP::Get.new(uri)
  request['User-Agent'] = 'forest-candles-merchant-audit/1.0'

  response = Net::HTTP.start(uri.host, uri.port, use_ssl: uri.scheme == 'https') do |http|
    http.request(request)
  end

  unless response.is_a?(Net::HTTPSuccess)
    raise "HTTP #{response.code} for #{url}"
  end

  JSON.parse(response.body)
end

def fetch_store_products(store_domain, max_pages)
  products = []
  since_id = 0

  1.upto(max_pages) do |_page|
    url = "https://#{store_domain}/products.json?limit=250&since_id=#{since_id}"
    payload = http_get_json(url)
    batch = payload.fetch('products', [])
    break if batch.empty?

    products.concat(batch)
    since_id = batch.last.fetch('id').to_i
    break if batch.size < 250
  end

  products
end

def read_products_from_file(path)
  payload = JSON.parse(File.read(path))
  products = payload['products']
  raise "Expected JSON object with top-level 'products' array in #{path}" unless products.is_a?(Array)

  products
end

def read_csv_with_optional_name_preamble(path)
  content = File.read(path)
  content = content.sub(/\AName:.*\n/, '')
  CSV.parse(content, headers: true)
end

def parse_product_and_variant_id(item_id)
  match = item_id.to_s.match(/shopify_[^_]+_(\d+)_(\d+)/)
  return [nil, nil] unless match

  [match[1].to_i, match[2].to_i]
end

def format_bool(value)
  value ? 'yes' : 'no'
end

def load_settings_data(path)
  return {} unless File.exist?(path)

  content = File.read(path)
  # settings_data.json starts with a block comment generated by Shopify.
  content = content.sub(%r{\A/\*.*?\*/\s*}m, '')
  payload = JSON.parse(content)
  payload.fetch('current', {})
rescue StandardError => e
  warn "Warning: failed to parse #{path}: #{e.message}"
  {}
end

def merchant_settings_status(settings)
  emit_shipping = settings.fetch('merchant_schema_emit_shipping_details', false)
  shipping_country = settings.fetch('merchant_shipping_country', 'US').to_s.strip
  shipping_rate = settings.fetch('merchant_shipping_rate', '').to_s.strip
  free_threshold = settings.fetch('merchant_free_shipping_threshold', '').to_s.strip

  emit_return_policy = settings.fetch('merchant_schema_emit_return_policy', false)
  accepts_returns = settings.fetch('merchant_accepts_returns', true)
  return_country = settings.fetch('merchant_return_country', 'US').to_s.strip
  return_days = settings.fetch('merchant_return_days', '').to_s.strip

  {
    emit_shipping: emit_shipping,
    shipping_country: shipping_country,
    shipping_rate: shipping_rate,
    free_threshold: free_threshold,
    shipping_schema_ready: emit_shipping && !shipping_country.empty? && (!shipping_rate.empty? || !free_threshold.empty?),
    emit_return_policy: emit_return_policy,
    accepts_returns: accepts_returns,
    return_country: return_country,
    return_days: return_days
  }
end

def audit_products(products, store_domain)
  product_by_id = {}
  rows = []

  products.each do |product|
    product_id = product['id'].to_i
    product_by_id[product_id] = product

    product_title = product['title'].to_s.strip
    handle = product['handle'].to_s.strip
    product_url = handle.empty? ? '' : "https://#{store_domain}/products/#{handle}"
    description = strip_html(product['body_html'])
    vendor = product['vendor'].to_s.strip
    product_type = product['product_type'].to_s.strip
    images = Array(product['images'])

    product_missing_critical = []
    product_missing_critical << 'title' if product_title.empty?
    product_missing_critical << 'description' if description.empty?
    product_missing_critical << 'link' if handle.empty?
    product_missing_critical << 'brand' if vendor.empty?

    has_https_image = images.any? { |image| image['src'].to_s.start_with?('https://') }
    product_missing_critical << 'image' unless has_https_image

    product_missing_recommended = []
    product_missing_recommended << 'product_type' if product_type.empty?

    variants = Array(product['variants'])

    if variants.empty?
      rows << {
        product_id: product_id,
        variant_id: nil,
        handle: handle,
        title: product_title,
        url: product_url,
        missing_critical_fields: (product_missing_critical + ['price', 'availability']).uniq,
        missing_recommended_fields: product_missing_recommended,
        vendor: vendor,
        product_type: product_type
      }
      next
    end

    variants.each do |variant|
      variant_missing_critical = product_missing_critical.dup
      variant_missing_recommended = product_missing_recommended.dup

      price_raw = variant['price'].to_s.strip
      variant_missing_critical << 'price' if price_raw.empty? || price_raw.to_f <= 0
      variant_missing_critical << 'availability' if variant['available'].nil?

      sku = variant['sku'].to_s.strip
      barcode = variant['barcode'].to_s.strip
      variant_missing_recommended << 'sku_or_barcode' if sku.empty? && barcode.empty?

      unless barcode.empty?
        barcode_digits = barcode.gsub(/\D/, '')
        unless VALID_GTIN_LENGTHS.include?(barcode_digits.length)
          variant_missing_recommended << 'barcode_not_valid_gtin_length'
        end
      end

      next if variant_missing_critical.empty? && variant_missing_recommended.empty?

      rows << {
        product_id: product_id,
        variant_id: variant['id'],
        handle: handle,
        title: product_title,
        url: product_url,
        missing_critical_fields: variant_missing_critical.uniq,
        missing_recommended_fields: variant_missing_recommended.uniq,
        vendor: vendor,
        product_type: product_type
      }
    end
  end

  [rows, product_by_id]
end

def write_csv_report(path, rows)
  CSV.open(path, 'w') do |csv|
    csv << [
      'product_id',
      'variant_id',
      'handle',
      'title',
      'url',
      'missing_critical_fields',
      'missing_recommended_fields',
      'vendor',
      'product_type'
    ]

    rows.each do |row|
      csv << [
        row[:product_id],
        row[:variant_id],
        row[:handle],
        row[:title],
        row[:url],
        row[:missing_critical_fields].join('|'),
        row[:missing_recommended_fields].join('|'),
        row[:vendor],
        row[:product_type]
      ]
    end
  end
end

def write_markdown_summary(path:, store_domain:, products_count:, field_gap_rows:, critical_gap_rows:, issue_rows:, missing_shipping_rows:, missing_shipping_report_rows:, settings_status:, missing_shipping_products:)
  File.open(path, 'w') do |f|
    f.puts "# Google Merchant Audit Summary"
    f.puts
    f.puts "- Generated at: #{Time.now.utc.iso8601}"
    f.puts "- Store domain: `#{store_domain}`"
    f.puts "- Products audited: #{products_count}"
    f.puts "- Variant rows with any merchant gap: #{field_gap_rows.size}"
    f.puts "- Variant rows with critical merchant gaps: #{critical_gap_rows.size}"
    f.puts

    f.puts "## Merchant Theme Settings Status"
    f.puts
    f.puts "- Emit shippingDetails: #{format_bool(settings_status[:emit_shipping])}"
    f.puts "- Shipping country: `#{settings_status[:shipping_country]}`"
    f.puts "- Shipping rate configured: #{format_bool(!settings_status[:shipping_rate].empty?)}"
    f.puts "- Free shipping threshold configured: #{format_bool(!settings_status[:free_threshold].empty?)}"
    f.puts "- Shipping schema ready: #{format_bool(settings_status[:shipping_schema_ready])}"
    f.puts "- Emit MerchantReturnPolicy: #{format_bool(settings_status[:emit_return_policy])}"
    f.puts "- Accept returns: #{format_bool(settings_status[:accepts_returns])}"
    f.puts "- Return country: `#{settings_status[:return_country]}`"
    f.puts "- Return days configured: #{format_bool(!settings_status[:return_days].empty?)}"
    f.puts

    if issue_rows
      f.puts "## Merchant Center Product Issues CSV"
      f.puts
      f.puts "- Total rows: #{issue_rows.size}"
      issue_counts = issue_rows.group_by { |r| r['Issue title'] }.transform_values(&:size)
      issue_counts.sort_by { |_, count| -count }.each do |issue, count|
        f.puts "- #{issue}: #{count}"
      end
      f.puts "- Missing shipping rows: #{missing_shipping_rows.size}"
      f.puts "- Missing shipping unique item IDs: #{missing_shipping_rows.map { |r| r['Item ID'] }.uniq.size}"
      f.puts
    end

    if missing_shipping_report_rows
      f.puts "## Missing Shipping Export"
      f.puts
      f.puts "- Total rows: #{missing_shipping_report_rows.size}"
      impact_counts = missing_shipping_report_rows.group_by { |r| r['Impact on product'] }.transform_values(&:size)
      impact_counts.sort_by { |_, count| -count }.each do |impact, count|
        f.puts "- #{impact}: #{count}"
      end
      f.puts
    end

    if missing_shipping_products.any?
      f.puts "## Shipping-Blocked Products (Sample)"
      f.puts
      missing_shipping_products.first(25).each do |entry|
        f.puts "- #{entry[:title]} (`#{entry[:item_id]}`)"
      end
      f.puts
      f.puts "Total shipping-blocked products found in issue CSV: #{missing_shipping_products.size}"
      f.puts
    end

    f.puts "## Exit Criteria"
    f.puts
    f.puts "- Critical field gaps must be 0 for clean product metadata coverage."
    f.puts "- Missing shipping rows must be 0 in Merchant Center exports for full approval."
  end
end

options = parse_options

products = if options[:products_json]
             read_products_from_file(options[:products_json])
           else
             fetch_store_products(options[:store_domain], options[:max_pages])
           end

field_gap_rows, product_by_id = audit_products(products, options[:store_domain])
critical_gap_rows = field_gap_rows.select { |row| row[:missing_critical_fields].any? }

issue_rows = nil
missing_shipping_rows = []
missing_shipping_products = []

if options[:issues_csv]
  issue_rows = read_csv_with_optional_name_preamble(options[:issues_csv])
  missing_shipping_rows = issue_rows.select { |row| row['Issue title'] == 'Missing shipping information' }

  seen_product_ids = {}

  missing_shipping_rows.each do |row|
    product_id, = parse_product_and_variant_id(row['Item ID'])
    next unless product_id
    next if seen_product_ids[product_id]

    product = product_by_id[product_id]

    missing_shipping_products << {
      item_id: row['Item ID'],
      product_id: product_id,
      title: row['Title'] || (product && product['title']) || 'Unknown product'
    }

    seen_product_ids[product_id] = true
  end
end

missing_shipping_report_rows = nil
if options[:missing_shipping_csv]
  missing_shipping_report_rows = read_csv_with_optional_name_preamble(options[:missing_shipping_csv])
end

settings = load_settings_data(options[:settings_data])
settings_status = merchant_settings_status(settings)

FileUtils.mkdir_p(options[:output_dir])
critical_report_path = File.join(options[:output_dir], 'google-merchant-critical-field-gaps.csv')
summary_report_path = File.join(options[:output_dir], 'google-merchant-audit-summary.md')

write_csv_report(critical_report_path, field_gap_rows)
write_markdown_summary(
  path: summary_report_path,
  store_domain: options[:store_domain],
  products_count: products.size,
  field_gap_rows: field_gap_rows,
  critical_gap_rows: critical_gap_rows,
  issue_rows: issue_rows,
  missing_shipping_rows: missing_shipping_rows,
  missing_shipping_report_rows: missing_shipping_report_rows,
  settings_status: settings_status,
  missing_shipping_products: missing_shipping_products
)

puts "Products audited: #{products.size}"
puts "Variant rows with any merchant field gaps: #{field_gap_rows.size}"
puts "Variant rows with critical gaps: #{critical_gap_rows.size}"

if issue_rows
  puts "Merchant issue rows: #{issue_rows.size}"
  puts "Missing shipping rows: #{missing_shipping_rows.size}"
  puts "Missing shipping unique item IDs: #{missing_shipping_rows.map { |r| r['Item ID'] }.uniq.size}"
end

if missing_shipping_report_rows
  impacted_not_approved = missing_shipping_report_rows.count { |row| row['Impact on product'] == 'Not approved' }
  puts "Missing shipping export rows: #{missing_shipping_report_rows.size}"
  puts "Missing shipping export not approved rows: #{impacted_not_approved}"
end

puts "Shipping schema ready in theme settings: #{format_bool(settings_status[:shipping_schema_ready])}"
puts "CSV report: #{critical_report_path}"
puts "Summary report: #{summary_report_path}"

exit_code = 0
exit_code = 1 if critical_gap_rows.any?
exit_code = 2 if missing_shipping_rows.any?
exit exit_code
